@apiUrl = http://localhost:3000/api
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjdiMDI2NjQ5OTEyNDQ3NTNhNmUxOGUiLCJub21lIjoiQWJlbGhhIGFsdGVyYWRvIiwiaWF0IjoxNjU0NjUxNDI4LCJleHAiOjE2NTQ2NTUwMjh9.87iiI2ZCUU01A4RDb5M2MCw8YLQ53so5CdWr0AikTwQ

# Obter a lista de solicitantes
GET http://localhost:3000/api/solicitantes
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Inserir novo solicitante
POST http://localhost:3000/api/solicitantes
Content-Type: application/json

{
 "nome": "Solicitante teste 2", "email": "teste2@upf.br",
 "celular": "99999-9889", "senha": "1234"
}
###

# Alterar solicitante
PUT http://localhost:3000/api/solicitantes
Content-Type: application/json

{
 "_id": "628d674c7c27b90665eafa4c",
 "nome": "Joao alterado",
 "email": "joao_solicitante@gmail.com",
 "senha": "abcd"
}
###


# Excluir um solicitante
DELETE http://localhost:3000/api/solicitantes/623a57de7e688588c0316e49
Content-Type: application/json
###


# Obter pelo id de solicitante
GET http://localhost:3000/api/solicitantes/623a6af66779e0de8514e4a3
Content-Type: application/json
###


# Obter solicitante filtrando
GET http://localhost:3000/api/solicitantes/filtro/alterado
Content-Type: application/json
###

# Autenticação de colaborador
POST {{apiUrl}}/solicitantes/login
Content-Type: application/json
x-auth-token: {{authToken}}

{
    "email": "abelha@abelha.com",
    "senha": "123"
}
###