# Obter a lista de colaborador - teste de GET
GET http://localhost:3000/colaborador
Content-Type: application/json
###

# Inserir novo colaborador
POST http://localhost:3000/colaborador
Content-Type: application/json

{
 "nome": "Eduarda",
 "email": "eduarda@gmail.com",
 "senha": 12345
}
###

# Alterar um colaborador
PUT http://localhost:3000/colaborador
Content-Type: application/json

{
 "_id": "",
 "nome": "",
 "email": "",
 "senha": 
}
###

# Excluir um colaborador pelo id
DELETE http://localhost:3000/animais/6227e892243ed4f07d7ca0e8
Content-Type: application/json
###

# Obter colaborador pelo id
GET http://localhost:3000/colaborador/6227e8d6243ed4f07d7ca0e9
Content-Type: application/json
###

# Obter colaborador filtrando
GET http://localhost:3000/colaborador/filtro/ga
Content-Type: application/json
###